//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coventry_University_Learning_Styles.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class covunilsdbEntities : DbContext
    {
        public covunilsdbEntities()
            : base("name=covunilsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Age> Ages { get; set; }
        public virtual DbSet<ClassCode> ClassCodes { get; set; }
        public virtual DbSet<Ethnicity> Ethnicities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<IndividualSession> IndividualSessions { get; set; }
        public virtual DbSet<SessionResult> SessionResults { get; set; }
        public virtual DbSet<LearningDifficulty> LearningDifficulties { get; set; }
        public virtual DbSet<StudentLearningDifficulty> StudentLearningDifficulties { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
