//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coventry_University_Learning_Styles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndividualSession()
        {
            this.SessionResults = new HashSet<SessionResult>();
        }
    
        public int ID { get; set; }
        public int ClassCodeID { get; set; }
        public int GenderID { get; set; }
        public int AgeID { get; set; }
        public int EthinicityID { get; set; }
        public Nullable<int> VisualCount { get; set; }
        public Nullable<int> AuralCount { get; set; }
        public Nullable<int> ReadWriteCount { get; set; }
        public Nullable<int> KineastheticCount { get; set; }
    
        public virtual Age Age { get; set; }
        public virtual ClassCode ClassCode { get; set; }
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionResult> SessionResults { get; set; }
    }
}
