//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coventry_University_Learning_Styles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionResult()
        {
            this.Ages = new HashSet<Age>();
            this.Ethnicities = new HashSet<Ethnicity>();
            this.Genders = new HashSet<Gender>();
        }
    
        public int ID { get; set; }
        public int IndividualSessionID { get; set; }
        public string Results { get; set; }
        public decimal VisualPercent { get; set; }
        public decimal AuralPercent { get; set; }
        public decimal ReadWritePercent { get; set; }
        public decimal KineastheticPercent { get; set; }
        public Nullable<bool> Satisfied { get; set; }
    
        public virtual IndividualSession IndividualSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Age> Ages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ethnicity> Ethnicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gender> Genders { get; set; }
    }
}
