//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coventry_University_Learning_Styles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLearningDifficulty
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int LearningDifficultyID { get; set; }
    
        public virtual LearningDifficulty LearningDifficulty { get; set; }
        public virtual Student Student { get; set; }
    }
}
